# Generated by Django 3.1.5 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num_canciones', models.SmallIntegerField()),
                ('fechaEstreno', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('artista', models.ManyToManyField(to='BeatSharkApp.Artista')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('contraseña', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FavCancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ManyToManyField(to='BeatSharkApp.Cancion')),
                ('usuario', models.ManyToManyField(to='BeatSharkApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='FavArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ManyToManyField(to='BeatSharkApp.Artista')),
                ('usuario', models.ManyToManyField(to='BeatSharkApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='FavAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ManyToManyField(to='BeatSharkApp.Album')),
                ('usuario', models.ManyToManyField(to='BeatSharkApp.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CancionArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.ManyToManyField(to='BeatSharkApp.Artista')),
                ('cancion', models.ManyToManyField(to='BeatSharkApp.Cancion')),
            ],
        ),
        migrations.AddField(
            model_name='cancion',
            name='genero',
            field=models.ManyToManyField(to='BeatSharkApp.Genero'),
        ),
        migrations.CreateModel(
            name='AlbumCancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ManyToManyField(to='BeatSharkApp.Album')),
                ('cancion', models.ManyToManyField(to='BeatSharkApp.Cancion')),
            ],
        ),
    ]
