# Generated by Django 3.1.5 on 2021-01-13 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BeatSharkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='fechaEstreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='num_canciones',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
