# Generated by Django 3.1.2 on 2020-10-29 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeatSharkApp', '0002_auto_20201029_0019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Cancion',
        ),
    ]
