# Generated by Django 3.1.5 on 2021-01-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatSharkApp', '0002_auto_20210113_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_canciones',
            field=models.SmallIntegerField(),
        ),
    ]
