# Generated by Django 3.1.2 on 2020-10-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeatSharkApp', '0003_auto_20201029_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='genero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BeatSharkApp.genero'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.SmallIntegerField(default=1),
        ),
    ]
