# Generated by Django 3.1.5 on 2021-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeatSharkApp', '0004_albumcancion_cancionartista_favalbum_favartista_favcancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
